//=========================================================
// src/myProject_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "main.h"

#include <SI_EFM8BB3_Register_Enums.h> // SFR declarations
#include "InitDevice.h"
#include "si_toolchain.h"

#include "synth_interface/synth_common.h"
#include "utility.h"
#include "led_controls.h"
#include "touch_keys.h"

#include "button_functions/page0.h"
#include "button_functions/page1.h"
#include "button_functions/page2.h"
#include "button_functions/page3.h"

#include "persistance.h"
#include "touch_keys.h"

typedef void(*BUTTON_FUNC)(uint8_t f);

BUTTON_FUNC code BUTTON_1_FUNC[4] = {&b0F0, &b0F1, &b0F2, &b0F3};
BUTTON_FUNC code BUTTON_2_FUNC[4] = {&b1F0, &b1F1, &b1F2, &b1F3};
BUTTON_FUNC code BUTTON_3_FUNC[4] = {&b2F0, &b2F1, &b2F2, &b2F3};

BUTTON_FUNC * code B_FUNC_PAGES[3] = {BUTTON_1_FUNC, BUTTON_2_FUNC, BUTTON_3_FUNC};

// $[Generated Includes]
// [Generated Includes]$

uint8_t last_result[4];
uint16_t touch_timer[4];
uint8_t hold_ctr[4];

uint8_t button4Functions()
{
  uint8_t i = 3;

  //short: change page, long: reset

  if (hold_ctr[i] > RESET_HOLD_COUNT)
    P0_B3 = 1;

  else if (hold_ctr[i] > 8)
  {
    hold_ctr[i]++;
    touch_timer[i] = millis();
    PCA0CPH4 = 0xF2;
    PCA0CPM4 |= (1 << 1);
    return 1;
  }
  else if (hold_ctr[i] > 3)
  {
    hold_ctr[i]++;
    touch_timer[i] = millis();
    PCA0CPH4 = 0xFF;
    PCA0CPM4 |= (1 << 1);
    return 1;
  }
  else if (hold_ctr[i] > 0)
  {
    hold_ctr[i]++;
    touch_timer[i] = millis();
    return 1;
  }
  else
  {
    //short press

    hold_ctr[i]++;
    touch_timer[i] = millis();
    PCA0CPH4 = 0xF2;
    PCA0CPM4 |= (1 << 1);
    return 1;
  }

  return 0;
}

/**
 * button 4 (top) short press
 */
void button4ShortPress()
{
  //switch page
  active_config.function_page++;
  if (active_config.function_page > 3)
    active_config.function_page = 0;

  //show page indicator animation
  funcPageLEDAni(active_config.function_page);
}


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}


//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void)
{
  uint16_t i = 0, k = 0;
  uint8_t result[4] = {0, 0, 0, 0};

  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();

  delayMS(2000);

  LED_InitRoutine(); //fade up

  if(!read_cfg())
  {
    calibrateTouch();
    write_cfg();
  }

  delayMS(250);

  funcPageLEDAni(active_config.function_page); //page indicator

  init_synth_mode();

  while (1)
  {
    petDog();

    sampleTouchSensors();

    for (i = 0; i < 4; i++)
      result[i] = (b_touch_timer[i] > active_config.touch_cal[i]); //1 touched, 0 no touch

    for (i = 0; i < 4; i++)
    {
      if (((result[i] == last_result[i]) && hold_ctr[i] == 0) || (millis() - touch_timer[i]) < 250)
        continue;
      else
      {
        touch_timer[i] = millis();

        if (result[i]) //button is touched
        {
          if(i < BUTTON_4)
            B_FUNC_PAGES[i][active_config.function_page](0);
          else
            button4Functions();

          continue;
        }

        if (i == BUTTON_4 && hold_ctr[BUTTON_4] < 3)
          button4ShortPress();

          if (i < BUTTON_4 && hold_ctr[i] < SHORT_PRESS_MAX_HOLD_COUNT)
            B_FUNC_PAGES[i][active_config.function_page](SHORT_PRESS);

        hold_ctr[i] = 0;
        last_result[i] = result[i];
      }

      resetLED();
    }

    // $[Generated Run-time code]
    // [Generated Run-time code]$
  }
}
